rem working directory

set workdir=%~dp0
cd %workdir%
cd tmp

python test0.py
python test1.py
python test2.py
python test3.py
python test4.py
python test5.py
python test6.py
python test7.py
python test8.py
python test9.py
python test10.py
python test11.py
python test12.py
python test13.py
python test14.py
python test15.py
python test16.py
python test17.py
python test18.py
python test19.py
python test20.py
python test21.py
python test22.py
python test23.py
python test24.py
python test25.py
python test26.py
python test27.py
python test28.py
python test29.py
python test30.py
python test31.py
python test32.py
python test33.py
python test34.py
python test35.py
python test36.py
python test37.py
python test38.py
python test39.py
python test40.py
python test41.py
python test42.py
python test43.py
python test44.py
python test45.py
python test46.py
python test47.py
python test48.py
python test49.py

cd %workdir%
